### ISSUE TITLE
Use template literals for better readability

### ISSUE THREAD

**Issue by joostf** [deannabosschert/web-app-from-scratch-1920#11]
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/60dc00604faefafcba92a9b94240f302ccef174e/docs/js/app.js#L9

On this line and in other parts of your code..

**Comment by deannabosschert** [comment]
Thanks!  Fixed it a while ago (directly after your presentation about Routing, Templating and Modules) but might have done this in a branch that hadn't been merged yet. 

```js
 const apiLink = `${endpoint}/repos${minor}${course}${year}${tag}?per_page=${limit}` 
```

![fixed it, gif](https://media.giphy.com/media/26ufcQZ7gnLOhR6Lu/giphy.gif)
