### ISSUE TITLE
Code comments in English

### ISSUE THREAD

**Issue by joostf** [deannabosschert/web-app-from-scratch-1920#12]
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/60dc00604faefafcba92a9b94240f302ccef174e/docs/js/app.js#L24

And altough it's hilarious, maybe reconsider the 'tone of voice' 😉

**Comment by deannabosschert** [comment]
Hahaha, of course I will remove all of those comments once getting to the end.
All of the comments in the final product will be in English anyways :)


![profanity](https://gifimage.net/wp-content/uploads/2018/06/watch-yo-profanity-gif-5.gif)
