### ISSUE TITLE
Redundant URL

### ISSUE THREAD

**Issue by bazottie** [deannabosschert/web-app-from-scratch-1920#17]
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/2440c2af26dd613ec443be412ecfd4b8493c3a3a/docs/js/app.js#L12

You build up the URL with variables, but you also have the full URL in your code. This seems redundant and I would suggest you remove it

**Comment by deannabosschert** [comment]
Removed!

![fixed it, gif](https://media.giphy.com/media/26ufcQZ7gnLOhR6Lu/giphy.gif)
