### ISSUE TITLE
URL build

### ISSUE THREAD

**Issue by bazottie** [deannabosschert/web-app-from-scratch-1920#18]
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/2440c2af26dd613ec443be412ecfd4b8493c3a3a/docs/js/app.js#L13

You could try constructing this api with template literals and even a URL object instance.
This would improve readability and usability

**Comment by deannabosschert** [comment]
Had it already fixed in the branch I was working in back then hahaha, but it's in template literals on the master branch aswell now. I'll ask you about the URL object instance next week  👀 

![fixed it, gif](https://media.giphy.com/media/26ufcQZ7gnLOhR6Lu/giphy.gif)
