### ISSUE TITLE
The good

### ISSUE THREAD

**Issue by DanielvandeVelde** [deannabosschert/web-app-from-scratch-1920#4]
Tof dat je CSS variabele gebruikt! Dat is iets waar ik zelf ook eens mee moet beginnen.
Dat zal het stylen een stuk efficienter maken als deze app groeit in grootte.

De font-size die je gebruikt ziet er ook heel interessant uit:
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/css/styles.css#L15
Ik ben benieuwd wat daar de gedachte achter is.

**Comment by deannabosschert** [comment]
't baseert de font-size op je window op dat moment.
Moet zeggen dat ik nog geen idee heb hoe 't precies werkt tho lol, maar thanks!
Denk dat ik het anders mss/wss gewoon alsnog met EM ga doen vanuit een standard style guide

https://css-tricks.com/snippets/css/fluid-typography/
