### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by DanielvandeVelde** [deannabosschert/web-app-from-scratch-1920#5]
Op dit moment wanneer de pagina wordt geladen zit er nog niets in de localStorage.
Helaas zoekt jouw app op dit moment wel gelijk in de localStorage of er iets te vinden valt.

Een makkelijke manier om dit op te lossen en waardoor je de code ook een stuk netter maak is om dingen op te delen in functies. Momenteel werk je op 1 functie na in de global scope.

Als je als eerst de functie aanroept waar je de aanvraag doet en wanneer deze aanvraag voltooid is de elementen voor de pagina maakt dan loopt alles direct goed. Dan kun je ook voordat je de aanvraag doet even kijken in de localStorage of de aanvraag wel nodig is.

**Comment by deannabosschert** [comment]
Yess, I figured dat ik 't beste eerst de routing kon fixen/adden aangezien daarmee toch de hele code op de schop moet. Nu staat alles nog vet lelijk in de global scope, da's alleen zodat ik dus geen dubbel refactor-werk doe zometeen lol

**Comment by deannabosschert** [comment]
Thanks!

![fixed it gif](https://media.giphy.com/media/26ufcQZ7gnLOhR6Lu/giphy.gif)
