### ISSUE TITLE
ForEcach

### ISSUE THREAD

**Issue by DanielvandeVelde** [deannabosschert/web-app-from-scratch-1920#6]
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/js/app.js#L33
Je gebruikt hier een .forEach maar je zou ook best goed een .map() kunnen gebruiken.
Er is niets mis met een forEach maar .map() is ook super fijn.
Voor de voordelen hiervan zijn er super veel goede artikelen zoals deze:
https://codeburst.io/javascript-map-vs-foreach-f38111822c0f

Overigens maak je daaronder voor alles elementen aan om deze in je html te stoppen. 
Het beste kan je om deze blokken een `<article>` zetten om deze ook mooi en semantisch correct houden.

**Comment by deannabosschert** [comment]
Nice! Heb de article-tags toegevoegd, is idd veel netter

**Comment by deannabosschert** [comment]
Thank u!

 ```js
  return data.map(data => { 
```

![fixed it, gif](https://media.giphy.com/media/26ufcQZ7gnLOhR6Lu/giphy.gif)
