### ISSUE TITLE
More comments 

### ISSUE THREAD

**Issue by tnanhekhan** [deannabosschert/web-app-from-scratch-1920#7]
Not quite sure what https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/js/app.js#L46 does
or why there are so many API keys. 
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/js/app.js#L4
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/js/app.js#L5
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/js/app.js#L6
https://github.com/deannabosschert/web-app-from-scratch-1920/blob/5a4ce016341252d1c80998f696c36624838bedd6/docs/js/app.js#L7

**Comment by deannabosschert** [comment]
De API-keys zijn geadd om mee te kunnen developen; deze API biedt maar 150 api-calls per dag aan dus ik wil er zometeen doorheen loopen. Heb wel vast de drie extra keys aangemaakt en erin gegooid, ook in case ik nu al tussendoor aan de limit zit. Dan comment ik de eerste uit en pak ik de tweede for now.

**Comment by deannabosschert** [comment]
Filterarray filtert alleen de benodigde info per item uit de ontvangen api-response. Je krijgt initially namelijk best wat info terug wat er niet uit te halen is in de query, en ik wil graag m'n data in advance cleanen voor het accessed wordt in m'n html-template zo
