### ISSUE TITLE
Link in repo description is not the link to the demo

### ISSUE THREAD

**Issue by tnanhekhan** [deannabosschert/web-app-from-scratch-1920#8]
Link in repo desc is: https://deannabosschert.github.io/web-app-from-scratch-1920/
While actual demo link is: https://wafs.netlify.com/

**Comment by deannabosschert** [comment]
gaan beide naar deploys, ene is alleen gehost op netlify en andere op github pages.
Had 'm al gedeployed naar netlify voordat er verteld werd dat iedereen 't op pages moest doen, dus vandaar. Ik check nog even of ik écht per se moet deployen op pages, maar zoniet houd ik liever alleen netlify. Vind ook de deploy previews en checks fijn werken.
